# fly.toml app configuration file generated for shopify-auction on 2024-06-29T19:14:57+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'shopify-auction'
primary_region = 'hkg'

[build]
[[services]]
internal_port = 4000
protocol = "tcp"

[[services.ports]]
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  PORT = "8081"
  SHOPIFY_APP_URL = "https://shopify-auction.fly.dev"
  SHOPIFY_API_KEY = "a9896d72741bd015197b16bab41f472c"
  SCOPES = "read_customers,read_files,read_orders,read_products,read_themes,write_customers,write_files,write_orders,write_products,write_themes"

[[restart]]
policy = "never"
retries = 10
processes = ["app"]