# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a9896d72741bd015197b16bab41f472c"
name = "auction-app"
handle = "auction-app-23"
application_url = "https://studies-addressing-loving-upgrades.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "trungvt-store.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://studies-addressing-loving-upgrades.trycloudflare.com/auth/callback",
  "https://studies-addressing-loving-upgrades.trycloudflare.com/auth/shopify/callback",
  "https://studies-addressing-loving-upgrades.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
