# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c0237746d5feff0054b309baee1f1f36"
name = "thanhnt-discount-app"
application_url = "https://writer-asthma-connectors-defence.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "sstrikess-test-discount-app.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://writer-asthma-connectors-defence.trycloudflare.com/auth/callback",
  "https://writer-asthma-connectors-defence.trycloudflare.com/auth/shopify/callback",
  "https://writer-asthma-connectors-defence.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
